== SUBMITION (2019-06-12 15:42:32) 
-- CODE:
from numpy import *
v = array(eval(input("Faltas: ")))
b = 0
for y in v:
	if(y%2 != 0):
		b = 1
p = zeros(b, dtype = int)
x = 0
g = 0
for r in v:
	if(r % 2!=0):
		p[x] = v[g]
		x = 1
	g = 1
print(p)
	

-- EXECUTION TIME:
0.904916
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1800/2572/main.py", line 12, in <module>
    p[x] = v[g]
IndexError: index 1 is out of bounds for axis 0 with size 1

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-06-12 15:44:11) 
-- CODE:
from numpy import *
v = array(eval(input("Faltas: ")))
b = 0
for y in v:
	if(y%2 != 0):
		b = b + 1
p = zeros(b, dtype = int)
x = 0
g = 0
for r in v:
	if(r % 2!=0):
		p[x] = v[g]
		x = x + 1
	g = g + 1
print(p)
	

-- EXECUTION TIME:
1.29352
-- TEST CASE 1:
---- input:
[75247561,76546316,75713658,97135671,70356874]
---- correct output:
[75247561 97135671]
---- user output:
[75247561 97135671]
-- TEST CASE 2:
---- input:
[13017594,57417542,85024758,12475981,75942785,91875987,29584192,85794217]
---- correct output:
[12475981 75942785 91875987 85794217]
---- user output:
[12475981 75942785 91875987 85794217]
-- TEST CASE 3:
---- input:
[31874903,74902746,23742046]
---- correct output:
[31874903]
---- user output:
[31874903]
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
