== SUBMITION (2019-03-11 15:22:00) 
-- CODE:
print(50//3(50%3))
-- EXECUTION TIME:
0.164412
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1331/main.py", line 1, in <module>
    print(50//3(50%3))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:23:22) 
-- CODE:
print(50//3)
print(50%3)
-- EXECUTION TIME:
0.175479
-- TEST CASE 1:
---- input:
xx
---- correct output:
16
2
---- user output:
16
2
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
