== TEST (2019-05-29 18:41:38) 
-- CODE:
from math import *
v1 = int(input(["tipo de magia :"]))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input(["tipo de magia :"]))
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:42:15) 
-- CODE:
from math import *
v1 = int(eval(["tipo de magia :"]))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(eval(["tipo de magia :"]))
TypeError: eval() arg 1 must be a string, bytes or code object
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:42:16) 
-- CODE:
from math import *
v1 = int(eval(["tipo de magia :"]))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(eval(["tipo de magia :"]))
TypeError: eval() arg 1 must be a string, bytes or code object
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:42:23) 
-- CODE:
from math import *
v1 = int(input(["tipo de magia :"]))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input(["tipo de magia :"]))
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:42:37) 
-- CODE:
from math import *
v1 = int(input("tipo de magia :"))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input())
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:42:56) 
-- CODE:
from math import *
v1 = int(input("tipo de magia :"))
print(v1)
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input())
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:51:52) 
-- CODE:
from math import *
v1 = int(input("tipo de magia :"))

-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input())
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-29 18:55:40) 
-- CODE:
from math import *
v1 = int(input("tipo de magia :"))

-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    v1 = int(input())
ValueError: invalid literal for int() with base 10: '["GELO","ILUSAO","CHOQUE"]'
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
