== TEST (2019-03-12 22:02:21) 
-- CODE:
aresta = 5
area = 3/2*(3)**0.5(5)**2
print(round(area, 4))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    area = 3/2*(3)**0.5(5)**2
TypeError: 'float' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-12 22:02:24) 
-- CODE:
aresta = 5
area = 3/2*(3)**0.5(5)**2
print(round(area, 4))
-- EXECUTION TIME:
0.21476
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1332/main.py", line 2, in <module>
    area = 3/2*(3)**0.5(5)**2
TypeError: 'float' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-03-13 14:04:18) 
-- CODE:
aresta = 5
area = 3/2*(3)**0.5(5)**2
print(round(area, 4))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    area = 3/2*(3)**0.5(5)**2
TypeError: 'float' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-03-13 14:07:38) 
-- CODE:
aresta = 5
area =3/2*(3)**0.5(5)**2
print(round(area,4))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    area =3/2*(3)**0.5(5)**2
TypeError: 'float' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-03-13 14:07:55) 
-- CODE:
aresta = 5
area =3 / 2*(3)**0.5(5)**2
print(round(area,4))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    area =3 / 2*(3)**0.5(5)**2
TypeError: 'float' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-03-13 19:27:33) 
-- CODE:
aresta = 5
area = 3 / 2 * (3) ** 0.5 * (5) ** 2
print(round(area,4))
-- OUTPUT:
64.9519
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-13 19:27:38) 
-- CODE:
aresta = 5
area = 3 / 2 * (3) ** 0.5 * (5) ** 2
print(round(area,4))
-- EXECUTION TIME:
0.15751
-- TEST CASE 1:
---- input:
xxx
---- correct output:
64.9519
---- user output:
64.9519
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
