== SUBMITION (2019-03-11 15:23:23) 
-- CODE:
print(50/3(50%3))
-- EXECUTION TIME:
0.12434
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1331/main.py", line 1, in <module>
    print(50/3(50%3))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:24:11) 
-- CODE:
print(50//3(50%3))
-- EXECUTION TIME:
0.16691
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1331/main.py", line 1, in <module>
    print(50//3(50%3))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:24:39) 
-- CODE:
print(50%3)
-- EXECUTION TIME:
0.176346
-- TEST CASE 1:
---- input:
xx
---- correct output:
16
2
---- user output:
2
-- GRADE:
0%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:26:18) 
-- CODE:
print(50//3)
print(50%3)
-- EXECUTION TIME:
0.126374
-- TEST CASE 1:
---- input:
xx
---- correct output:
16
2
---- user output:
16
2
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
